version: '3.9'

services:
  java_app:
    container_name: java.app
    image: appimage
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.mail.host=sandbox.smtp.mailtrap.io
      - spring.mail.port=2525
      - spring.mail.username=17d85f2b63dbe8
      - spring.mail.password=95133832a1f7ff
      - spring.mail.properties.smtp.auth=true
      - spring.mail.properties.smtp.starttls.enable=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://java_db:3306/alquileres_maria?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      java_db:
        condition: service_healthy
  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=alquileres_maria
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  db_data: